import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Provider from "./Provider";
import { AuthProvider } from "./_context/AuthContext";
import { AdminProvider } from "./_context/AdminContext";
import { getIsAdmin } from "./_actions/admin";
import { Toaster } from "@/components/ui/sonner";
import ChatWidget from "./_components/ChatWidget";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAdmin = await getIsAdmin();
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <AuthProvider>
          <AdminProvider isAdmin={isAdmin}>
            <Provider>{children}</Provider>
            <Toaster position="top-center" />
            <ChatWidget />
          </AdminProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
